# import * from './Status.gql'
mutation UpdateOrder($orderId: ID!, $clientId: ID!, $descricao: String!, $valor: Float!, $status: Status! ) {
  
  updateOrder(
    orderId: $orderId,
    clientId: $clientId,
    descricao: $descricao,
    valor: $valor,
    status: $status
  ){
    id
    descricao
    status
    valor
    client {
      id
      nome
      telefone
      endereco
    }
  }
}