mutation CreateClient($nome: String!, $telefone: String!, $endereco: String!){
  createClient(
    nome: $nome
    telefone: $telefone
    endereco: $endereco
  ){
    id
    nome
    telefone
    endereco
  }
}