mutation updateClient($id: ID!, $nome: String!, $endereco: String!, $telefone: String! ) {
  
  updateClient(
    clientId: $id,
    nome: $nome,
    endereco: $endereco,
    telefone: $telefone
  ){
    id
    nome
    endereco
    telefone
    user {
      id
      nome
      email
    }

  }
}